//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int MessageTypeId { get; set; }
        public int TransactionTypeId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public int StatusId { get; set; }
        public int ProducerId { get; set; }
        public int ConsumerId { get; set; }
        public int FileTypeId { get; set; }
        public string MessageContent { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual MessageConsumer MessageConsumer { get; set; }
        public virtual MessageProducer MessageProducer { get; set; }
        public virtual MessageStatus MessageStatus { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
