//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Domain;
    
    public partial class MessageTrackingDBEntities : DbContext
    {
        public MessageTrackingDBEntities()
            : base("name=MessageTrackingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FileType> FileType { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<MessageConsumer> MessageConsumer { get; set; }
        public DbSet<MessageProducer> MessageProducer { get; set; }
        public DbSet<MessageStatus> MessageStatus { get; set; }
        public DbSet<MessageType> MessageType { get; set; }
        public DbSet<TransactionType> TransactionType { get; set; }
    }
}
